art/config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :performances
  resources :shows
  resources :performers
  resources :users

  root 'home#trending'
  get 'calendar.:format', to: 'performances#calendar', as: 'calendar'
end

art/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :performance_id, :rating, :review)
    end
end

art/app/helpers/reviews_helper.rb
module ReviewsHelper
end

art/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :performance_id %><br>
    <%= f.text_field :performance_id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

art/app/views/reviews/_review.html.erb
<tr>
  <td><%= review.performance.show.name %></td>
  <td><%= review.rating %></td>
  <td><%= review.review %></td>
  <td><%= link_to 'Show', review %></td>
</tr>

art/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

art/app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Performance</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user.name %></td>
        <td><%= review.performance.show.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.review %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

art/app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

art/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= link_to @review.user.name, @review.user %>
</p>

<p>
  <strong>Performance:</strong>
  <%= link_to @review.performance.show.name, @review.performance %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>