art/config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :performances
  resources :shows
  resources :performers
  resources :users

  root 'home#trending'
  get 'calendar.:format', to: 'performances#calendar', as: 'calendar'
end

art/app/models/performer.rb
class Performer < ActiveRecord::Base
  has_and_belongs_to_many :shows
  has_many :performances, through: :shows

  validates :name, presence: true
  validates :description, presence: true

  def average_rating
    sum = 0
    count = 0
    performances.each do |performance|
      performance.reviews.each do |review|
        count += 1
        sum += review[:rating]
      end
    end

    count.zero? ? nil : sum / count
  end
end

art/app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  before_action :set_performer, only: [:show, :edit, :update, :destroy]

  # GET /performers
  # GET /performers.json
  def index
    @performers = Performer.all
  end

  # GET /performers/1
  # GET /performers/1.json
  def show
  end

  # GET /performers/new
  def new
    @performer = Performer.new
  end

  # GET /performers/1/edit
  def edit
  end

  # POST /performers
  # POST /performers.json
  def create
    @performer = Performer.new(performer_params)

    respond_to do |format|
      if @performer.save
        format.html { redirect_to @performer, notice: 'Performer was successfully created.' }
        format.json { render :show, status: :created, location: @performer }
      else
        format.html { render :new }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performers/1
  # PATCH/PUT /performers/1.json
  def update
    respond_to do |format|
      if @performer.update(performer_params)
        format.html { redirect_to @performer, notice: 'Performer was successfully updated.' }
        format.json { render :show, status: :ok, location: @performer }
      else
        format.html { render :edit }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performers/1
  # DELETE /performers/1.json
  def destroy
    @performer.destroy
    respond_to do |format|
      format.html { redirect_to performers_url, notice: 'Performer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performer
      @performer = Performer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def performer_params
      params.require(:performer).permit(:name, :description)
    end
end

art/app/helpers/performers_helper.rb
module PerformersHelper
end

art/app/views/performers/_form.html.erb
<%= form_for(@performer) do |f| %>
  <% if @performer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performer.errors.count, "error") %> prohibited this performer from being saved:</h2>

      <ul>
      <% @performer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

art/app/views/performers/edit.html.erb
<h1>Editing performer</h1>

<%= render 'form' %>

<%= link_to 'Show', @performer %> |
<%= link_to 'Back', performers_path %>

art/app/views/performers/index.html.erb
<h1>Listing performers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @performers.each do |performer| %>
      <tr>
        <td><%= performer.name %></td>
        <td><%= performer.description %></td>
        <td><%= link_to 'Show', performer %></td>
        <td><%= link_to 'Edit', edit_performer_path(performer) %></td>
        <td><%= link_to 'Destroy', performer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performer', new_performer_path %>

art/app/views/performers/new.html.erb
<h1>New performer</h1>

<%= render 'form' %>

<%= link_to 'Back', performers_path %>

art/app/views/performers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @performer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @performer.description %>
</p>

<%= link_to 'Edit', edit_performer_path(@performer) %> |
<%= link_to 'Back', performers_path %>