art/config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :performances
  resources :shows
  resources :performers
  resources :users

  root 'home#trending'
  get 'calendar.:format', to: 'performances#calendar', as: 'calendar'
end

art/app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :show
  has_many :reviews, dependent: :destroy

  validates :performed_on, presence: true
  validates :show, presence: true

  scope :upcoming, -> { where("performed_on > ?", 1.month.ago).includes(:show) }

  def average_rating
    return unless reviews.any?

    total_rating = reviews.inject(0) do |total, review|
      total + review.rating
    end
    total_rating / reviews.length
  end

  def to_ical
    OpenStruct.new.tap do |e|
      e.dtstart       = Icalendar::Values::Date.new(performed_on)
      e.dtend         = Icalendar::Values::Date.new(performed_on + 1.day)
      e.summary       = show.name
      e.description   = show.description
      e.ip_class      = "PRIVATE"
    end
  end
end

art/app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_performance, only: [:show, :edit, :update, :destroy]

  # GET /performances
  # GET /performances.json
  def index
    @performances = Performance.all
  end

  # GET /performances/1
  # GET /performances/1.json
  def show
  end

  # GET /performances/new
  def new
    @performance = Performance.new
  end

  # GET /performances/1/edit
  def edit
  end

  # POST /performances
  # POST /performances.json
  def create
    @performance = Performance.new(performance_params)

    respond_to do |format|
      if @performance.save
        format.html { redirect_to @performance, notice: 'Performance was successfully created.' }
        format.json { render :show, status: :created, location: @performance }
      else
        format.html { render :new }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performances/1
  # PATCH/PUT /performances/1.json
  def update
    respond_to do |format|
      if @performance.update(performance_params)
        format.html { redirect_to @performance, notice: 'Performance was successfully updated.' }
        format.json { render :show, status: :ok, location: @performance }
      else
        format.html { render :edit }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performances/1
  # DELETE /performances/1.json
  def destroy
    @performance.destroy
    respond_to do |format|
      format.html { redirect_to performances_url, notice: 'Performance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /calendar.ics
  def calendar
    @calendar = EventCalendar.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance
      @performance = Performance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def performance_params
      params.require(:performance).permit(:show_id, :performed_on)
    end
end

art/app/helpers/performances_helper.rb
module PerformancesHelper
end

art/app/views/performances/_form.html.erb
<%= form_for(@performance) do |f| %>
  <% if @performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@performance.errors.count, "error") %> prohibited this performance from being saved:</h2>

      <ul>
      <% @performance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.text_field :show_id %>
  </div>
  <div class="field">
    <%= f.label :performed_on %><br>
    <%= f.date_select :performed_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

art/app/views/performances/calendar.ics.erb
<%= @calendar.ical %>

art/app/views/performances/calendar.text.erb
<%= @calendar.ical %>

art/app/views/performances/edit.html.erb
<h1>Editing performance</h1>

<%= render 'form' %>

<%= link_to 'Show', @performance %> |
<%= link_to 'Back', performances_path %>

art/app/views/performances/index.html.erb
<h1>Listing performances</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th>Performed on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td><%= performance.show %></td>
        <td><%= performance.performed_on %></td>
        <td><%= link_to 'Show', performance %></td>
        <td><%= link_to 'Edit', edit_performance_path(performance) %></td>
        <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performance', new_performance_path %>

art/app/views/performances/new.html.erb
<h1>New performance</h1>

<%= render 'form' %>

<%= link_to 'Back', performances_path %>

art/app/views/performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @performance.show %>
</p>

<p>
  <strong>Performed on:</strong>
  <%= @performance.performed_on %>
</p>

<%= link_to 'Edit', edit_performance_path(@performance) %> |
<%= link_to 'Back', performances_path %>